version: '3.8'

services:
  rentiflat:
    image: rentiflat:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - APP_PORT=8080
      - SECRET_KEY=my_secret_key
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Sac@2121
      - DB_NAME=rentiflat
      - DB_SSLMODE=disable
    depends_on:
      - postgres
    networks:
      - rentiflat-network

  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sac@2121
      - POSTGRES_DB=rentiflat
    networks:
      - rentiflat-network

networks:
  rentiflat-network:
    driver: bridge
