# Stage 1: Build the Go application
FROM golang:1.23.2 AS builder

# Set the working directory
WORKDIR /app

# Copy the Go Modules manifests
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Install swag
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Run swagger init
RUN swag init

# Build the application
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o rentiflatapp .

# Stage 2: Create the Distroless image
FROM gcr.io/distroless/base-debian10

# Set the working directory
WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/rentiflatapp .

# Copy Swagger files (if needed in the final image)
COPY --from=builder /app/docs ./docs

# Command to run the binary
CMD ["./rentiflatapp"]
